name: Lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: Pyright on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - run: |
            uvx -p ${{ matrix.python-version }} pyright

  ruff:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: Ruff on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - run: |
            uvx -p ${{ matrix.python-version }} ruff check