name: Lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: Pyright on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - run: |
            py -m pip install .
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          python-version: ${{ matrix.python-version }}
          warnings: true

  ruff:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(vars.PYTHON_VERSIONS) }}

    name: Ruff on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - run: |
            uvx -p ${{ matrix.python-version }} ruff check